import test from "node:test";
import assert from "node:assert/strict";
import { isImplicitHeadingText, isStandaloneCodeParagraph, shouldEnhanceCodeBlock } from "../src/reader/heuristics.js";

test("does not treat article prose as a code block", () => {
  const prose = "As inference demand surges, existing datacenters are quickly reaching full utilization and companies are trying to build new ones as fast as possible.";

  assert.equal(isStandaloneCodeParagraph(prose), false);
});

test("does not enhance a preformatted RFC quotation as code", () => {
  const quotation =
    "The ORIGIN attribute is generated by the speaker that originates the associated routing information. Its value SHOULD NOT be changed by any other speaker.";

  assert.equal(shouldEnhanceCodeBlock(quotation, { preformatted: true }), false);
});

test("still enhances real preformatted code and explicitly labelled code", () => {
  assert.equal(shouldEnhanceCodeBlock("const route = { origin: 'IGP' };", { preformatted: true }), true);
  assert.equal(
    shouldEnhanceCodeBlock("This example intentionally reads like a sentence.", { preformatted: true, explicitLanguage: true }),
    true
  );
});

test("recognizes extracted plain-text section titles as TOC headings", () => {
  const titleVariants = new Set();
  const text = "Datacenters matter more than ever";

  assert.equal(isImplicitHeadingText(text, text.toLowerCase(), titleVariants), true);
});


test("rejects article title variants as implicit headings", () => {
  const text = "How the hell is Groq raising more money?";
  const titleVariants = new Set([text.toLowerCase()]);

  assert.equal(isImplicitHeadingText(text, text.toLowerCase(), titleVariants), false);
});
